import { type NextPage } from 'next'
import Head from 'next/head'

import { api } from '~/utils/api'
import { Spinner } from '~/components/ui/Spinner'
import SubmitTask from '~/components/SubmitTask'
import PageLayout from '~/components/ui/Layout'
import Task from '~/components/Task'

const Home: NextPage = () => {
  const { data, isLoading } = api.tasks.get.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <SubmitTask />
        {isLoading && <Spinner size={8} color="neutral-100" />}
        {data?.map((task) => (
          <Task key={task.id} task={task} />
        ))}
      </PageLayout>
    </>
  )
}

export default Home
